version: "3.8"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hemi
    container_name: hemi
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hemi_nginx:
    image: nginx:alpine
    container_name: hemi_nginx
    restart: unless-stopped
    ports:
      - 8070:70
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/hemitest.conf:/etc/nginx/conf.d/hemitest.conf
    networks:
      - app_network

  db:
    container_name: db-hemi
    image: postgres:latest
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
